config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :campaigns
  root 'campaigns#index'

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  monetize :amount_to_raise_cents
  mount_uploader :picture, PictureUploader
  
  belongs_to :category
  belongs_to :owner, foreign_key: 'owner_id', class_name: 'User'

  validates :title, presence: true, length: { maximum: 100 }
  validates :amount_to_raise, presence: true, numericality: { greater_than_or_equal_to: 500 }
  validates :picture, presence: true
  validates :category, presence: true
  validates :story, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
		 
  has_many :campaigns, foreign_key: 'owner_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_campaign, only: [:show]
  before_action :find_campaign_to_edit, only: [:edit, :update, :destroy]
  
  def index
    @campaigns = Campaign.all.order('created_at DESC')
  end

  def new
    @campaign = current_user.campaigns.build
  end

  def create
    @campaign = current_user.campaigns.build(campaign_params)
	
    if @campaign.save
      redirect_to root_path, notice: "Campaign #{@campaign.title} was successfully created."
    else
      render 'new'
    end
  end

  def show
  end
  
  def edit
  end
  
  def update
	if @campaign.update(campaign_params)
	  redirect_to campaign_path(@campaign)
	else
	  render 'edit'
	end
  end

  def destroy
	@campaign.destroy
	redirect_to root_path, notice: "Campaign #{@campaign.title} was successfully destroyed."
  end
  
  private

    def campaign_params
      params.require(:campaign).permit(:title, :short_description, :amount_to_raise, :category_id, :picture, :picture_cache, :story, :video_url)
    end

    def find_campaign
      @campaign = Campaign.find(params[:id])
    end
	
	def find_campaign_to_edit
	  @campaign = current_user.campaigns.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.haml
= simple_form_for @campaign do |f|
  = f.input :title
  = f.input :short_description
  = f.input :amount_to_raise
  = f.hidden_field(:picture_cache)
  = f.input :picture
  = f.input :video_url
  = f.association :category, prompt: 'Select Category'
  = f.input :story, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'mini'} }
  %br
  .text-center
    = f.button :submit, ( f.object.new_record? ? "Start a Campaign" : "Update Campaign"), class: 'btn-primary'
  %br
  
:javascript
  $(window).on('page:before-unload', function(e){
    if (CKEDITOR && CKEDITOR.instances) {
      for(name in CKEDITOR.instances) {
        if (CKEDITOR.instances.hasOwnProperty(name)) {
          CKEDITOR.instances[name].destroy(true);
        }
      }
    }
  });

app/views/campaigns/edit.html.haml
%section#edit-campaign
  %h1.header Edit Campaign
  = render 'form'

app/views/campaigns/index.html.haml
%section#campaigns
  .row
    - @campaigns.each do |campaign|
      .col-md-3.col-sm-4.col-xs-6.col-xxs-12
        = link_to campaign_path(campaign), class:'campaign-card' do
          = image_tag(campaign.picture_url(:thumbnail), alt: campaign.title, class: 'img-responsive')
          .campaign-details
            .cause
              - if campaign.category.present?
                .category= campaign.category.name
              .title= campaign.title
              .description= campaign.short_description
            .meta
              .amount-raised= Money.from_amount(9686.0).format 
              .progress
                .progress-bar{role: 'progressbar',
                aria: {valuenow: '60', valuemin: '0', valuemax: '100'},
                style: "width: #{Money.from_amount(9686.0)/campaign.amount_to_raise*100}%"}

app/views/campaigns/new.html.haml
%section#new-campaign
  %h1.header Start Campaign
  %p.sub-header Raise funds for creative, entrepreneurial, or other passion projects.
  = render 'form'

app/views/campaigns/show.html.haml
%section#campaign-page
  .campaign-header
    .row
      .col-sm-7
        - if @campaign.video_url.present?
          .embed-responsive.embed-responsive-16by9
            %iframe.embed-responsive-item{src: @campaign.video_url}
        - else
          = image_tag(@campaign.picture_url, alt: @campaign.title, class: 'img-responsive')  
      .col-sm-5
        %h1.title= @campaign.title
        %p.description= @campaign.short_description
        %p.owner= @campaign.owner.email
        .progress
          .progress-bar{role: 'progressbar', aria: {valuenow: '60', valuemin: '0', valuemax: '100'}, style: "width: #{Money.from_amount(9686.0)/@campaign.amount_to_raise*100}%"} 
        %span= "#{Money.from_amount(9686.0)/@campaign.amount_to_raise*100}% of #{@campaign.amount_to_raise.format}"
        %span= @campaign.end_at
  .campaign-body
    .row
      .col-sm-7
        .story
          = @campaign.story.html_safe
      .col-sm-5
	
  .actions
    = link_to 'Edit', edit_campaign_path
    = link_to 'Delete', campaign_path, method: :delete, data: { confirm: 'Are you sure?' }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Crowdfunding
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body

    %nav.navbar.navbar-default
      .container
        <!-- Brand and toggle get grouped for better mobile display -->
        .navbar-header
          %button.navbar-toggle.collapsed{type: 'button', data: {toggle: 'collapse', target: '#navbar-collapse-1'}, aria: {expanded: 'false'}}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Crowdfunding!', root_path, class: 'navbar-brand'
        #navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to 'Explore', root_path
            %li= link_to 'How it works', root_path
          %ul.nav.navbar-nav.navbar-right
            %li= link_to 'Start A Campaign', new_campaign_path, class: "btn btn-primary start-campaign"
            - if user_signed_in?
              %li= link_to 'Log out', destroy_user_session_path, method: :delete
            - else
              %li= link_to 'Sign Up', new_user_registration_path
              %li= link_to 'Log In', new_user_session_path

    .container
      - if notice.present?
        %p.notice= notice
      - if alert.present?
        %p.alert= alert
      = yield